// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMxifeiNpeXJ9iKQy58Rq73nLllQexwqA',
    appId: '1:449242395448:web:7bd1a5407b95e4782087cd',
    messagingSenderId: '449242395448',
    projectId: 'my-notes-flutter-9d6e6',
    authDomain: 'my-notes-flutter-9d6e6.firebaseapp.com',
    storageBucket: 'my-notes-flutter-9d6e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyl4ghnQYwhcvEcaevcBh9jTCaqc0vank',
    appId: '1:449242395448:android:f233ce9a7f91d6292087cd',
    messagingSenderId: '449242395448',
    projectId: 'my-notes-flutter-9d6e6',
    storageBucket: 'my-notes-flutter-9d6e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuacOlFjubufGdiE_nzsouAQWhzqS3Xfw',
    appId: '1:449242395448:ios:731969759f06c8c72087cd',
    messagingSenderId: '449242395448',
    projectId: 'my-notes-flutter-9d6e6',
    storageBucket: 'my-notes-flutter-9d6e6.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuacOlFjubufGdiE_nzsouAQWhzqS3Xfw',
    appId: '1:449242395448:ios:731969759f06c8c72087cd',
    messagingSenderId: '449242395448',
    projectId: 'my-notes-flutter-9d6e6',
    storageBucket: 'my-notes-flutter-9d6e6.firebasestorage.app',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMxifeiNpeXJ9iKQy58Rq73nLllQexwqA',
    appId: '1:449242395448:web:bac5e40b630029fe2087cd',
    messagingSenderId: '449242395448',
    projectId: 'my-notes-flutter-9d6e6',
    authDomain: 'my-notes-flutter-9d6e6.firebaseapp.com',
    storageBucket: 'my-notes-flutter-9d6e6.firebasestorage.app',
  );
}
